### ISSUE TITLE
Item Frames Turn Invisible Without Sneak + Right-Click

### ISSUE THREAD

**Issue by AetheriMC** [lamaprogramer/ToggleableItemFrames#1]
Hello! This is for the Fabric version 2.1.0-1.19.3 but on Minecraft version 1.19.2.

While holding an item frame, the frames are perfectly visible and behave normally, but once I'm no longer holding an item frame, the frames immediately disappear. This happens without the need to crouch + r-click on the frame.

**Comment by williamk-jr** [comment]
Would you happen to be using the mod on a server?

**Comment by AetheriMC** [comment]
I am :)

**Comment by williamk-jr** [comment]
Ah ok, then this is intentional design. Due to some client-side limitations, I can't store the invisibility data on the client, so I had to cut some things out when using the mod on only the client.
