### ISSUE TITLE
Item frames stay invisible when holding another one on servers

### ISSUE THREAD

**Issue by ODF4** [lamaprogramer/ToggleableItemFrames#10]
**Minecraft version:** 1.21.1 (Fabric)
**Mod version:** 5.0.0
**Mod config (unchanged default):**
`{
  "showInvisibleFramesWhenHeld": true,
  "invisibleIfNotSupportedByServer": true
}`

**Behavior in singleplayer:**
Expected behavior, I can turn item frames invisible with shift + right click, and all invisible item frames become visible again if I'm holding one in my hand.

**Behavior on a private Aternos server (vanilla 1.21.1):**
All item frames are invisible by default and I can't toggle the item frames' visibility with shift + right click (as expected), BUT even if I hold an item frame in my hand all item frames stay invisible, when I expected them to become visible again for as long as I held the item frame in my hand.

I believe this might be a bug, but if not, I think it'd be nice to include an additional boolean in the config json such as "showInvisibleFramesWhenHeldOnServers".

Also, I only tested the mod in singleplayer and on the aforementioned server. I am not sure if the mod may behave differently on other servers.
I will gladly provide additional information if needed.

Thank you so much for your time and for developing this great mod!

**Comment by williamk-jr** [comment]
This was indeed a bug, it should be fixed now in version 5.1.0

**Comment by ODF4** [comment]
> This was indeed a bug, it should be fixed now in version 5.1.0

Wow, that was incredibly fast! I just tested the new version and I can confirm that the issue is fixed now, thank you so much!
