### ISSUE TITLE
incompatibility with "More Culling"

### ISSUE THREAD

**Issue by peow** [lamaprogramer/ToggleableItemFrames#3]
the new version of the mod dont work with More Culling "Custom Item Frame Renderer"
![image](https://github.com/lamaprogramer/ToggleableItemFrames/assets/105888751/a005a34d-6313-4aed-80d5-dde0bad30583)

it is possible to make the item frame invisible but when holding a item frame in your hand, the invisible item frames do not appear
![image](https://github.com/lamaprogramer/ToggleableItemFrames/assets/105888751/20e913d8-03b0-4743-89b4-748d2aa08383)

in the old version of your mod (2.1.2) there was no problem

if it is possible to fix this, please update to fabric 1.20.1

**Comment by williamk-jr** [comment]
Sorry for the late response, been a bit busy, I'll get on that right away!

**Comment by peow** [comment]
dont worry

**Comment by williamk-jr** [comment]
Alrighty, 4.0.0 is out now with the fixes and changes you mentioned

**Comment by peow** [comment]
you're the best
