### ISSUE TITLE
Items Disappearing 

### ISSUE THREAD

**Issue by Valerian9** [lamaprogramer/ToggleableItemFrames#6]
Sometimes when i rejoin my world after leaving it the items inside the item frame disappear and just get deleted, now im not 100 sure if its this mod because i am also using the ClickThrough mod so it might be because of that one, so im just reporting this problem to both.

**Comment by williamk-jr** [comment]
It was definitely my mod, very sorry about that, hopefully it didn't inconvenience you too much, I'll try and get a patch out in the next few hours.

**Comment by williamk-jr** [comment]
Alright, it's fixed!
